name: Update MLB Odds

on:
  schedule:
    - cron: '0 13 * * *'  # Runs every day at 9AM EST (13 UTC)
  workflow_dispatch:      # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run script
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: python mlb/mlb_odds_today.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Auto-update MLB odds"
          git push
