name: Update Streaks

on:
  schedule:
    - cron: '0 13 * * *'  # Runs daily at 9 AM ET
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run streak generation
      run: python generate_streaks.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add streaks.html
        git commit -m "Update streaks.html"
        git push
