name: Update MLB Odds

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *'  # 3 PM UTC = 11 AM ET daily

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python mlb/generate_games_html.py
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add mlb/index.html
          git commit -m "Update MLB odds"
          git push
