name: Update MLB Odds

on:
  workflow_dispatch:

jobs:
  update-odds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # You can skip this if no external packages are required
      - name: Install dependencies
        run: |
          if [ -f mlb/requirements.txt ]; then pip install -r mlb/requirements.txt; fi

      - name: Run script
        working-directory: ./mlb
        run: python generate_games_html.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add index.html
          git commit -m "Update MLB odds"
          git push
